name: Glorious
description: "A new Flutter project."
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.0.0
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  uuid: ^4.5.1
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  open_filex: ^4.7.0
  intl: ^0.19.0
  socket_io_client: ^2.0.0
  dio: ^5.4.3+1
  flutter_local_notifications: ^17.1.2
  web_socket_channel: ^3.0.3
  video_player: ^2.8.2
  flutter_webrtc: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
#This is a comment to force a dependency refresh
